Change return type from QMap to QMultiMap
QMultiMap no longer inherits QMap which causes the conversion to fail:
error C2440: 'return': cannot convert from 'const QMultiMap<QString,QString>' to 'QMap<QString,QString>'

Change-Id: Ie9c0b2588d0b0c27a81949926b36800f6f6c354c
Reviewed-by: Timur Pocheptsov <timur.pocheptsov@qt.io>
Reviewed-by: Mårten Nordheim <marten.nordheim@qt.io>